version: '2'

services:
  postfixserver:
    image: tvial/docker-mailserver
    hostname: mail
    domainname: domain.com
    links:
    - elk
    ports:
    - "25:25"
    volumes:
    - maildata:/var/mail
    - ./config/:/tmp/docker-mailserver/
    environment:
    - SMTP_ONLY=1
    - ENABLE_ELK_FORWARDER=1
    - ENABLE_SPAMASSASSIN=0
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=0
    - ENABLE_POSTGREY=0
    - ONE_DIR=0
    - DMS_DEBUG=0
    restart: always
  elk:
     build: elk
     ports:
     - "5601:5601"
     - "9200:9200"
     - "5044:5044"
     - "5000:5000"
     restart: always

volumes:
  maildata:
    driver: local
